<?php
/**
 * AddonsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Social Search
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: OpenAPI3.1.0.3
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

/**
 * AddonsTest Class Doc Comment
 *
 * @category    Class
 * @description Add on products that can be requested. Each add on is billable. These are optional parameters and can be omitted if not needed.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddonsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Addons"
     */
    public function testAddons()
    {
    }

    /**
     * Test attribute "direct_check"
     */
    public function testPropertyDirectCheck()
    {
    }

    /**
     * Test attribute "demographics"
     */
    public function testPropertyDemographics()
    {
    }

    /**
     * Test attribute "fraud_shield"
     */
    public function testPropertyFraudShield()
    {
    }
}
