<?php
/**
 * SocialSearchRespTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Social Search
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: OpenAPI3.1.0.3
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

/**
 * SocialSearchRespTest Class Doc Comment
 *
 * @category    Class
 * @description SocialSearchResp
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SocialSearchRespTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SocialSearchResp"
     */
    public function testSocialSearchResp()
    {
    }

    /**
     * Test attribute "address_information"
     */
    public function testPropertyAddressInformation()
    {
    }

    /**
     * Test attribute "consumer_identity"
     */
    public function testPropertyConsumerIdentity()
    {
    }

    /**
     * Test attribute "direct_check"
     */
    public function testPropertyDirectCheck()
    {
    }

    /**
     * Test attribute "employment_information"
     */
    public function testPropertyEmploymentInformation()
    {
    }

    /**
     * Test attribute "fraud_shield"
     */
    public function testPropertyFraudShield()
    {
    }

    /**
     * Test attribute "informational_message"
     */
    public function testPropertyInformationalMessage()
    {
    }

    /**
     * Test attribute "ssn"
     */
    public function testPropertySsn()
    {
    }

    /**
     * Test attribute "statement"
     */
    public function testPropertyStatement()
    {
    }
}
